Vehicle.MVC/Models/VehicleMakeView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Vehicle.Service.DAL;

namespace Vehicle.MVC.Models
{
    public class VehicleMakeView
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Abrv { get; set; }

        public virtual ICollection<VehicleModelView> VehicleModels { get; set; }
    }
}

Vehicle.MVC/Controllers/VehicleMakeController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vehicle.MVC.Models;
using Vehicle.Service.DAL;
using Vehicle.Service.Services;

namespace Vehicle.MVC.Controllers
{
    public class VehicleMakeController : Controller
    {
        VehicleMakeService make = new VehicleMakeService();
        
        public ActionResult Index(int? page, string sort, string search)
        {
            var sortPar = new Parameters.SortParameters() { Sort = sort };
            var filterPar = new Parameters.FilterParameters() { Search = search };
            var pagePar = new Parameters.PageParameters() { Page = page ?? 1, PageSize = 7 };
            var vehicleMake = make.Get(sortPar, filterPar, pagePar);
            ViewBag.sort = sort;
            ViewBag.name = sort == "name_desc" ? "name" : "name_desc";
            ViewBag.abrv = sort == "abrv_desc" ? "abrv" : "abrv_desc";
            ViewBag.search = search;
            var list = Mapper.Map<IEnumerable<VehicleMake>, IEnumerable<VehicleMakeView>>(vehicleMake);
            return View(new StaticPagedList<VehicleMakeView>(list, vehicleMake.GetMetaData()));
        }

        [HttpGet]
        public ActionResult Delete (int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var vehicleId = make.Find(id);
                if (vehicleId == null)
                {
                    return HttpNotFound();
                }
                return View(Mapper.Map<VehicleMakeView>(vehicleId));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(VehicleMakeView makes)
        {
            try
            {
                make.Delete(Mapper.Map<VehicleMake>(makes));
                return RedirectToAction("Index");
            }
            catch (Exception) { }
            return RedirectToAction("Delete", makes.Id);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Abrv")] VehicleMakeView makes)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    make.Create(Mapper.Map<VehicleMake>(makes));
                    return RedirectToAction("Index");
                }
            }
            catch (DataException) { }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var vehicleMake = make.Find(id);
                if (vehicleMake == null)
                {
                    return HttpNotFound();
                }
                return View(Mapper.Map<VehicleMakeView>(vehicleMake));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Abrv")] VehicleMakeView makes)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    make.Edit(Mapper.Map<VehicleMake>(makes));
                    return RedirectToAction("Index");
                }
            }
            catch (DataException) { }
            return RedirectToAction("Edit", makes.Id);
        }

    }
}

Vehicle.MVC/Views/VehicleMake/Create.cshtml
@model Vehicle.MVC.Models.VehicleMakeView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Create</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "VehicleMake", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <dl>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Make name" } })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control", @placeholder = "Abbreviation" } })
                        </dl>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick='window.location = "@Url.Action("Index", "VehicleMake")";'>
                    Back to List
                </button>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleMake/Delete.cshtml
@model Vehicle.MVC.Models.VehicleMakeView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Delete</h2>
                <h4>Are you sure you want to delete this?</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" style="font-size:16px">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayName("Make name:")
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayName("Abbreviation:")
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Abrv)
                        </dd>
                    </dl>
                </div>
            </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("Delete", "VehicleMake", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <button type="button" class="btn btn-primary"
                                    onclick='window.location = "@Url.Action("Index", "VehicleMake")";'>
                                Back to List
                            </button>
                        </div>
                    }
                </div>
            </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleMake/Edit.cshtml
@model Vehicle.MVC.Models.VehicleMakeView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Edit</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "VehicleMake", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <dl>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Make name" } })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control", @placeholder = "Abbreviation" } })
                        </dl>
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick='window.location = "@Url.Action("Index", "VehicleMake")";'>
                    Back to List
                </button>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleMake/Index.cshtml
@model IPagedList<Vehicle.MVC.Models.VehicleMakeView>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" type="text/css" href="~/Main.css">

<h2>Vehicle Makes</h2>
<br />
<div>
    <div class="row-no-gutters">
        <div class="col-xs-1 pull-left">
            <button type="button" class="btn btn-primary" onclick='window.location = "@Url.Action("Create", "VehicleMake")";'>Create</button>
        </div>
        @using (Html.BeginForm("Index", "VehicleMake"))
        {
            <div class="pull-right">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
            <div class="col-xs-3 pull-right">
                @Html.TextBox("search", null, new { @class = "form-control" ,  @placeholder="Searching by Make name & Abrv"})
            </div>
            <br />
        }
    </div>
</div>
<br />
<br />
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.ActionLink("Make name", "Index", new { sort = ViewBag.name, search = ViewBag.search })
        </th>
        <th>
            Model name
        </th>
        <th>
            @Html.ActionLink("Abbreviation", "Index", new { sort = ViewBag.abrv, search = ViewBag.search })
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td width="35%">
                @Html.DisplayFor(modelItem => item.Name)
                <div class="btn-group pull-right" role="group">
                    @if ((item.VehicleModels).Count < 1)
                    {
                        <button type="button" class="btn btn-danger btn-xs"
                                onclick='window.location = "@Url.Action("Delete", "VehicleMake", new { ID = item.Id })";'>
                            Delete
                        </button>
                    }
                    <button type="button" class="btn btn-success btn-xs"
                            onclick='window.location = "@Url.Action("Edit", "VehicleMake", new { ID = item.Id })";'>
                        Edit
                    </button>
                </div>
            </td>
            <td width="35%">
                @foreach (var modelsInMaker in item.VehicleModels)
                {
                    <p>
                        @Html.DisplayFor(modelItem => modelsInMaker.Name)
                    </p>
                }
            </td>
            <td width="30%">
                @Html.DisplayFor(modelItem => item.Abrv)
            </td>
        </tr>
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.search, sort = ViewBag.sort, direction = ViewBag.direction }))