Vehicle.MVC/Models/VehicleModelView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vehicle.MVC.Models
{
    public class VehicleModelView
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Abrv { get; set; }

        public int VehicleMakeId { get; set; }

        public virtual VehicleMakeView VehicleMake { get; set; }

        public IList<SelectListItem> VehicleMakes { get; set; }
    }
}

Vehicle.MVC/Controllers/VehicleModelController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vehicle.MVC.Models;
using Vehicle.Service.DAL;
using Vehicle.Service.Services;

namespace Vehicle.MVC.Controllers
{
    public class VehicleModelController : Controller
    {
        VehicleModelService model = new VehicleModelService();

        public ActionResult Index(int? page, string sort, string search)
        {
            var sortPar = new Parameters.SortParameters() { Sort = sort };
            var filterPar = new Parameters.FilterParameters() { Search = search };
            var pagePar = new Parameters.PageParameters() { Page = page ?? 1, PageSize = 10 };
            var vehicleModel = model.Get(sortPar, filterPar, pagePar);
            ViewBag.sort = sort;
            ViewBag.model = sort == "model_desc" ? "model" : "model_desc";
            ViewBag.make = sort == "make_desc" ? "make" : "make_desc";
            ViewBag.abrv = sort == "abrv_desc" ? "abrv" : "abrv_desc";
            ViewBag.search = search;
            var list = Mapper.Map<IEnumerable<VehicleModel>, IEnumerable<VehicleModelView>>(vehicleModel);
            return View(new StaticPagedList<VehicleModelView>(list, vehicleModel.GetMetaData()));
        }

        [HttpGet]
        public ActionResult Create()
        {
            VehicleModelView vehicleModel = new VehicleModelView()
            {
                VehicleMakes = Mapper.Map<IList<SelectListItem>>
                               (model.GetMakes().Select
                               (c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }))
            };
            return View(vehicleModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleModelView models)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Create(Mapper.Map<VehicleModel>(models));
                    return RedirectToAction("Index");
                }
            }
            catch (DataException) { }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var vehicleId = model.Find(id);
                if (vehicleId == null)
                {
                    return HttpNotFound();
                }
                return View(Mapper.Map<VehicleModelView>(vehicleId));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(VehicleModelView models)
        {
            try
            {
                model.Delete(Mapper.Map<VehicleModel>(models));
                return RedirectToAction("Index");
            }
            catch (Exception) { }
            return RedirectToAction("Delete", models.Id);
        }

        [HttpGet]
        public ActionResult Edit( int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var models = model.Find(id);
                if (models == null)
                {
                    return HttpNotFound();
                }
                var result = Mapper.Map<VehicleModel, VehicleModelView>(models);
                result.VehicleMakes = Mapper.Map<IList<SelectListItem>>
                                      (model.GetMakes().Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }));
                return View(result);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,VehicleMakeId,Name,Abrv")] VehicleModelView models)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Edit(Mapper.Map<VehicleModel>(models));
                    return RedirectToAction("Index");
                }
            }
            catch (DataException) { }
            return RedirectToAction("Edit", models.Id);
        }

    }
}

Vehicle.MVC/Views/VehicleModel/Create.cshtml
@model Vehicle.MVC.Models.VehicleModelView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Create</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "VehicleModel", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <dl>
                            @Html.DropDownListFor(model => model.VehicleMakeId, Model.VehicleMakes, new { @class = "form-control" })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Model name" } })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control", @placeholder = "Abbreviation" } })
                        </dl>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick='window.location = "@Url.Action("Index", "VehicleModel")";'>
                    Back to List
                </button>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleModel/Delete.cshtml
@model Vehicle.MVC.Models.VehicleModelView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Delete</h2>
                <h4>Are you sure you want to delete this?</h4>
            </div>
            <div class="modal-body" style="font-size:16px">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Make name:")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.VehicleMake.Name)
                    </dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Model name:")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Abbreviation:")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Abrv)
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "VehicleModel", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <button type="button" class="btn btn-primary"
                                onclick='window.location = "@Url.Action("Index", "VehicleModel")";'>
                            Back to List
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleModel/Edit.cshtml
@model Vehicle.MVC.Models.VehicleModelView
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Edit</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "VehicleModel", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <dl>
                            @Html.DropDownListFor(model => model.VehicleMakeId, Model.VehicleMakes, new { @class = "form-control" })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Model name" } })
                        </dl>
                        <dl>
                            @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control", @placeholder = "Abbreviation" } })
                        </dl>
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick='window.location = "@Url.Action("Index", "VehicleModel")";'>
                    Back to List
                </button>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Vehicle.MVC/Views/VehicleModel/Index.cshtml
@model IPagedList<Vehicle.MVC.Models.VehicleModelView>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" type="text/css" href="~/Main.css">

<h2>Vehicle Models</h2>
<br />
<div>
    <div class="row-no-gutters">
        <div class="pull-left">
            <button type="button" class="btn btn-primary" onclick='window.location = "@Url.Action("Create", "VehicleModel")";'>Create</button>
        </div>
        @using (Html.BeginForm("Index", "VehicleModel"))
        {
            <div class="pull-right">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
            <div class="col-xs-3 pull-right">
                @Html.TextBox("search", null, new { @class = "form-control",  @placeholder="Searching by All"})
            </div>
        }
        <br />
    </div>
</div>
<br />
<br />
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.ActionLink("Make name", "Index", new { sort = ViewBag.make, search = ViewBag.search })
        </th>
        <th>
            @Html.ActionLink("Model name", "Index", new { sort = ViewBag.model, search = ViewBag.search })
        </th>
        <th>
            @Html.ActionLink("Abbreviation", "Index", new { sort = ViewBag.abrv, search = ViewBag.search })
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td width="30%">
                @Html.DisplayFor(modelItem => item.VehicleMake.Name)
            </td>
            <td width="40%">
                @Html.DisplayFor(modelItem => item.Name)
                <div class="btn-group pull-right" role="group">
                        <button type="button" class="btn btn-danger btn-xs"
                                onclick='window.location = "@Url.Action("Delete", "VehicleModel", new { ID = item.Id })";'>
                            Delete
                        </button>
                    <button type="button" class="btn btn-success btn-xs"
                            onclick='window.location = "@Url.Action("Edit", "VehicleModel", new { ID = item.Id })";'>
                        Edit
                    </button>
                </div>
            </td>
            <td width="30%">
                @Html.DisplayFor(modelItem => item.Abrv)
            </td>
        </tr>
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.search, sort = ViewBag.sort, direction = ViewBag.direction }))